name: llm_project1
channels:
  - defaults
  - pytorch
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py310h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - certifi=2025.8.3=py310hecd8cb5_0
  - cffi=1.17.1=py310h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cpuonly=2.0=0
  - dav1d=1.2.1=h6c40b1e_0
  - expat=2.7.1=h6d0c2b6_0
  - filelock=3.17.0=py310hecd8cb5_0
  - fontconfig=2.14.1=h269ac6a_3
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.2.1=py310h2cec913_0
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py310hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43548
  - jinja2=3.1.6=py310hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libjpeg-turbo=2.0.0=hca72f7f_0
  - libpng=1.6.39=h6c40b1e_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py310h46256e1_0
  - mkl=2023.1.0=h8e150cf_43560
  - mkl-service=2.4.0=py310h46256e1_2
  - mkl_fft=1.3.8=py310h6c40b1e_0
  - mkl_random=1.2.4=py310ha357a0b_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py310hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - networkx=3.4.2=py310hecd8cb5_0
  - numpy=1.26.4=py310h827a554_0
  - numpy-base=1.26.4=py310ha186be2_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - pcre2=10.42=h9b97e30_1
  - pillow=11.3.0=py310h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py310hecd8cb5_0
  - python=3.10.18=hc958d9f_0
  - pytorch=2.2.2=py3.10_0
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.2=py310h46256e1_0
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py310hecd8cb5_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - sympy=1.13.3=py310hecd8cb5_1
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.15=h3a5a201_0
  - torchaudio=2.2.2=py310_cpu
  - torchvision=0.17.2=py310_cpu
  - urllib3=2.5.0=py310hecd8cb5_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - cachetools==6.2.6
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.5
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - openai==2.16.0
      - packaging==26.0
      - pandas==2.3.3
      - protobuf==6.33.5
      - pyarrow==23.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2026.1.15
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.2.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - streamlit==1.53.1
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
prefix: /Users/shengwei/opt/miniconda3/envs/llm_project1
